#!/bin/bash

#ipSAE
python3 37_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/ALK_axltide/ALK_axltide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 37_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/EGFRm_1csktide/EGFRm_1csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 37_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/MET_1csktide/MET_1csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 37_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/ROS1_csktide/ROS1_csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 37_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/SRC_1srctide/SRC_1srctide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

#ipSAE_min
python3 38_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/ALK_axltide/ALK_axltide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 38_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/EGFRm_1csktide/EGFRm_1csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 38_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/MET_1csktide/MET_1csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 38_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/ROS1_csktide/ROS1_csktide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

python3 38_generate_ipSAE_comparison_plots.py.py /work/RADONC/s226058/wspace/proDesign/kinase_pep_design/YST_fixed/original_subs/af2_init_guess/data/SRC_1srctide/SRC_1srctide_merged_scores_pTM-ipTM_with_oriSubs_SEQ_with_ipSAEmin_15_15.csv

